version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - webapp
      - keycloak
    restart: unless-stopped

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=vedablog
      - DB_PASSWORD=vedablog123
      - DB_NAME=vedablog
      - KEYCLOAK_URL=http://localhost:8081
      - KEYCLOAK_REALM=vedablog
      - KEYCLOAK_CLIENT_ID=vedablog-client
      - SESSION_SECRET=dev-secret-key-change-in-production
    depends_on:
      - postgres
      - keycloak
    volumes:
      - ./webapp:/app
      - /app/node_modules
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    command: start-dev
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data_dev: